config/routes.rb
Rails.application.routes.draw do

  get '/cars' => 'home#cars'
  get '/contact' => 'home#contact'
  get '/local' => 'home#local'
  get '/about' => 'home#about'

  get '/h1_van' => 'home#h1_van'
  get '/creta' => 'home#creta'
  get '/kia_rio_grey' => 'home#kia_rio_grey'
  get '/mitsubishi' => 'home#mitsubishi'

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  around_action :switch_locale
 
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
  
    def default_url_options
    { locale: I18n.locale }
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home_page = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/about.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>About Us</title>

</head>

<body>
	<H1>About Us</H1>

</body>
</html>

app/views/home/cars.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Cars</title>

</head>

<body>
	<H1>Cars</H1>

  <%= link_to image_tag('H1_van', width: '315', height: ' 225', :alt => "H1 van"), h1_van_path %>
	<%= link_to "Hyundai H1 12 person van", h1_van_path %><br> <br> <br> <br> <br>
  <br> <br> <br> <br>
  <%= link_to image_tag('Creta', width: '315', height: ' 225', :alt => "Hyundai Creta"), creta_path %>
	<%= link_to "Hyundai Creta SUV", creta_path %><br> <br> <br> <br> <br>
  <br> <br> <br> <br>
  <%= link_to image_tag('Kia1_grey', width: '315', height: ' 225', :alt => "Kia Rio"), kia_rio_grey_path %>
	<%= link_to "Kia Rio", kia_rio_grey_path %><br> <br> <br> <br> <br>
  <br> <br> <br> <br>
  <%= link_to image_tag('Kia2_grey', width: '315', height: ' 225', :alt => "Kia Rio"), kia_rio_grey_path %>
	<%= link_to "Kia Rio", kia_rio_grey_path %><br> <br> <br> <br> <br>
  <br> <br> <br> <br>
  <%= link_to image_tag('Mitsubishi', width: '315', height: ' 225', :alt => "Mitsubishi Mirage"), mitsubishi_path %>
	<%= link_to "Mitsubishi Mirage", mitsubishi_path %><br> <br> <br> <br> <br>
  <br>


</body>
</html>

app/views/home/contact.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Contact Us</title>

</head>

<body>
<center>

  <br> <br> <br> <br>
  <br> <br> <br> <br>

  <div class="businessName">
    <H1>Orquídeas Car Rentals<H1>
  </div>

  <div class="businessLocation">
    Avenida Oeste
    <br>Bajo Boquete
	</div>

  <div class="businessPhone">
    +507 6393 2521
  </div>

  <div class="businessEmail">
    orquideas.car.rentals@gmail.com
    <br>boquete.car.rentals@gmail.com
  </div>

  <div class="businessWebsite">
    orquideasboquete.com
    <br>boquetecarrentals.com
    <br>orquideascarrentals.com
  </div>

</center>

</body>
</html>

app/views/home/creta.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Creta</title>

</head>

<body>
	<H1>Creta</H1>

  <%= link_to image_tag('Creta', width: '315', height: ' 225', :alt => "Hyundai Creta"), creta_path %>
	<%= link_to "Hyundai Creta SUV", creta_path %><br> <br> <br> <br> <br>


</body>
</html>

app/views/home/h1_van.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>H1 Van</title>

</head>

<body>
	<H1>H1 Van</H1>

  <%= link_to image_tag('H1_van', width: '315', height: ' 225', :alt => "H1 van"), h1_van_path %>
	<%= link_to "Hyundai H1 12 person van", h1_van_path %><br> <br> <br> <br> <br>


</body>
</html>

app/views/home/index.html.erb
<body class="homepage">

  <h1><center><%= t :welcome_to_boquete %></center></h1>

  <p>
    <%= t :orquideas_intro %>
  </p>


</body>

app/views/home/kia_rio.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Kia Rio</title>

</head>

<body>
	<H1>Kia Rio</H1>

  <%= link_to image_tag('Kia1_grey', width: '315', height: ' 225', :alt => "Kia Rio"), kia_rio_grey_path %>
	<%= link_to "Kia Rio", kia_rio_grey_path %><br> <br> <br> <br> <br>

</body>
</html>

app/views/home/local.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Local Info</title>

</head>

<body>

	<H1>Local Info</H1>

</body>
</html>

app/views/home/mitsubishi.html.erb
<!-- This is the correct doc type for the css style sheets I'm using, as near as I can tell. *author's note to self -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
	<title>Mitsubishi</title>

</head>

<body>
	<H1>Mitsubishi</H1>

  <%= link_to image_tag('Mitsubishi', width: '315', height: ' 225', :alt => "Mitsubishi Mirage"), mitsubishi_path %>
	<%= link_to "Mitsubishi Mirage", mitsubishi_path %><br> <br> <br> <br> <br>

</body>
</html>

app/views/layouts/_language_selector.html.erb
<span class='language_selector'>
  <%= link_to_unless_current image_tag('iconfinder_flag-spain_748120_16', :alt => "Español"), locale: "es" %> |
  <%= link_to_unless_current image_tag('iconfinder_flag-united-kingdom_748024_16', :alt => "English"), locale: "en" %>
</span>

app/views/layouts/_navbar.html.erb
<div class="breadcrumbs"> <!-- Begin navigation (breadcrumbs) section -->

<center>
<table border="0" cellpadding="0" width='85%'>
<tr><td>
  <table style="border: 0px solid #000000; border-collapse: collapse;" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
      <td rowspan='1' width='15%' align="center">
        <MY_H4>
          <%= link_to 'Home', root_path %>
        </MY_H4>
      </td>

      <td rowspan='1' width='15%' align="center">
        <MY_H4>
          <%= link_to 'Cars', cars_path %>
        </MY_H4>
      </td>

      <td rowspan='1' width='15%' align="center">
        <MY_H4>
          <%= link_to 'Contact Us', contact_path %>
        </MY_H4>
      </td>

      <td rowspan='1' width='15%' align="center">
        <MY_H4>
          <%= link_to 'Local Info', local_path %>
        </MY_H4>
      </td>

      <td rowspan='1' width='15%' align="center">
        <MY_H4>
          <%= link_to 'About Us', about_path %>
        </MY_H4>
      </td>

  </table>
</td> </tr>
</table>
</center>

</div> <!-- End navigation (breadcrumbs) section -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orquídeas Car Rentals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='clear_div'></div>

    <%= render 'layouts/language_selector' %>

    <%= yield %>
  </body>
</html>